#!/bin/bash

if ! [ $EUID -ne 0 ]
then
	echo "Not run as root"
	exit 1
fi

if [ ! $# -eq 1 ]
then
	echo "Wrong count of arguments. Use of script: $0 <number>"
	exit 1
fi

LIMIT=$1
numRegex="^[0-9]+$"

if ! [[ $1 =~ $numRegex ]]
then
	echo "Not a number"
	exit 1
fi

allUsers=$(ps -eo user= | sort -n | uniq)
declare -A allUsersSum

for user in $allUsers
do
	allUsersSum[$user]=$(ps -U $user -u $user -o rss= | awk '{sum+=$1} END {print sum}' 2> /dev/null)
	echo "$user ${allUsersSum[$user]}"
done

for user in ${!allUsersSum[@]}
do
	if [ "${allUsersSum[$user]}" -gt "$1" ]
	then
		pids=$(ps -U $user -u $user -o rss=,pid= | awk -v limit=$LIMIT '$1 > limit {print $2}')

		for pid in $pids
		do 
			echo "Killing task with PID $pid of user $user due to higher RSS than limit $1"
		done
	fi
done
