#!/bin/bash

if ! [ $# -eq 1 ]
then
	echo "Wrong usage of the script! Correct usage: $0 <config_file>"
	exit 1
fi

if ! [ -e $1 ] || ! [ -f $1 ]
then
	echo "First argument must be an existing regular file"
fi

mainFile="fakeWakeup"
devices=$(cat $mainFile | tail -n +2 | sed 's/\t/ /g' | tr -s ' ' | cut -d' ' -f1)

declare -A deviceStatus
declare -A deviceNewStatus

for device in ${devices[@]}
do
	status=$(cat $mainFile | tail -n +2 | egrep "^$device" | sed 's/\t/ /g' | tr -s ' ' | cut -d' ' -f3 | sed 's/\*//g')
	deviceStatus[$device]=$status
done

for device in "${!deviceStatus[@]}"
do
	echo "$device -> ${deviceStatus[$device]}"
done

while read -r line
do
	if [ $(echo $line | egrep ".*#.*" | wc -l) -eq 1 ]
	then
		line=$(echo $line | cut -d'#' -f1)
	fi

	if ! [ -z "$line" ]
	then
		device=$(echo $line | awk '{print $1}' | sed 's/ //g')
		mode=$(echo $line | awk '{print $2}')
		flag=0

		for dev in ${devices[@]}
		do
			if [ $dev = $device ]
			then
				flag=1
			fi
		done

		if [ $flag -eq 0 ]
		then
			echo "No such device as: $device"
		else
			if [ $mode = "enabled" ] || [ $mode = "disabled" ]
			then
				deviceNewStatus[$device]=$mode

				if ! [ $mode = "${deviceStatus[$device]}" ]
				then
					echo "Will echo to $mainFile $device once!"
				else
					echo "Will not echo to $mainFile $device"
				fi
			else
				echo "Device status for device $device is not either enabled or disabled!"
			fi
		fi
	fi
done  < "$1"

