#!/bin/bash

whoUsers=($(who | awk '{print $1}'))
psUsers=($(ps -eo user= | sort -u))
flag=0

for psUser in "${psUsers[@]}"; do
	flag=0

	for whoUser in "${whoUsers[@]}"; do
		if [ "${psUser}" = "${whoUser}" ]
		then
			flag=1
			break
		fi
	done

	if [ "${flag}" -eq 0 ]
	then
		echo "${psUser}"
	fi
done
