#!/bin/bash

if ! [ $# -eq 2 ]
then
	echo "Wrong usage of the script! Correct usage: $0 <csv_file_1> <csv_file_2>"
	exit 1
fi

if ! [ -e $1 ]
then
	echo "First file does not exist!"
	exit 1
fi

if ! [ -e $2 ]
then
	echo "Second file does not exist!"
	exit 1
fi

if ! [ -f $1 ]
then
	echo "First argument is not a regular file!"
	exit 1
fi

if ! [ -f $2 ]
then
	echo "Second argument is not a regular file"
	exit 1
fi

# check for file ending

old_IFS=$IFS
IFS=$'\n'
firstFileSorted=$(cat $1 | sort -g -t':' -k1)

for line in $firstFileSorted
do
	flag=0
	lineData=$(echo $line | cut -d',' -f2-)
	secondFileData=$(cat $2)

	for line2 in $secondFileData
	do
		if [ $(echo $line2 | egrep "^[0-9]+,$lineData" | wc -l) -eq 1 ]
		then
			flag=1
			break
		fi
	done

	if [ $flag -eq 0 ]
	then
		echo $line >> $2
	fi
done

IFS=$old_IFS
